### ISSUE TITLE
EXM Send Fails - No Cities

### ISSUE THREAD

**Issue by digitalParkour** [Sitecore/xGenerator#21]
The send fails. 
I traced it to the GetRandomCity method. The issue is where it is loading cities by subcontinent from GeoIP cache. The error is fired when no cities exists.
It appears to be looking for the City data from a file named "ExperienceGenerator.Data.countryInfo.txt"
Where does this text file come from?

ManagedPoolThread #9 12:25:55 ERROR EXM Generator failed for campaign: 71b62829-0550-4c3a-8328-0cfb0d49d615
Exception: System.InvalidOperationException
Message: No items specified
Source: Colossus
   at Colossus.Statistics.WeightedSetBuilder`1.Build()
   at ExperienceGenerator.Services.GetRandomCityService.GetRandomCity(String subcontinentCode)

**Comment by steviemcg** [comment]
ExperienceGenerator.Data.countryInfo.txt is an embedded resource
