### ISSUE TITLE
MissingManifestResourceException

### ISSUE THREAD

**Issue by yaroskrinitskiy** [Sitecore/xGenerator#22]
It seems that xGen doesn’t work with Sitecore 8.2.1. The following exception can be found in the log files:
Exception System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "Sitecore.ExperienceAnalytics.Api.Resources.RegionResources.resources" was correctly embedded or linked into assembly "Sitecore.ExperienceAnalytics.Api" at compile time, or that all the satellite assemblies required are loadable and fully signed.
   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at ExperienceGenerator.Data.GeoDataCache.LoadRegionsFromResource()
   at ExperienceGenerator.Data.GeoDataCache.FromResource()
   at ExperienceGenerator.Repositories.GeoDataRepository.get_Cache()

It seems it’s due to the fact that the Sitecore.ExperienceAnalytics.Api.dll assembly doesn’t have _resources_
![image](https://cloud.githubusercontent.com/assets/14195501/24666793/fdd541ac-1969-11e7-8c7f-77572c080626.png)
whereas 8.2.0 does have... 
![image](https://cloud.githubusercontent.com/assets/14195501/24666722/d2eb9b26-1969-11e7-9594-e13f9492283c.png)

**Comment by jeanfrancoislarente** [comment]
I'm closing this issue due to its age and the fact that we've upgraded xGenerator to 9.x
